-- ───────────────────────────────────────────────────────────────
--  LENA — Esquema de base de datos (Supabase / PostgreSQL)
--  Ejecuta este script en el SQL Editor de tu proyecto Supabase de Lena.
--  Crea las dos tablas que el bot necesita: chats_lena y leads_lena.
-- ───────────────────────────────────────────────────────────────

-- Memoria de conversaciones (un row por intercambio user → assistant)
create table if not exists chats_lena (
  id                 bigint generated by default as identity primary key,
  user_id            text not null,                 -- número de WhatsApp del cliente
  message_content    text,                          -- mensaje del usuario
  assistant_response text,                          -- respuesta de Lena
  date_time          timestamptz not null default now()
);
create index if not exists chats_lena_user_id_idx on chats_lena (user_id);
create index if not exists chats_lena_date_time_idx on chats_lena (date_time);

-- Leads (un row por persona/número; guarda datos, etapa y seguimiento)
create table if not exists leads_lena (
  id_lead             bigint generated by default as identity primary key,
  id_usuario          text unique,                  -- número de WhatsApp (clave del lead)
  nombre_cliente      text,                          -- nombre de quien escribe
  paciente            text,                          -- nombre del paciente (si es para otra persona)
  edad                integer,
  para_quien          text,                          -- yo mismo | hija | hijo | pareja | ...
  sede                text,                          -- Piura | Chiclayo | Lima | Virtual
  motivo              text,                          -- procedimiento de interés
  psicologo_asignado  text,                          -- (heredado) aquí se guarda procedimiento_sugerido
  precalificacion     text,                          -- NUEVO | ALTO | MEDIO | BAJO
  dni_contacto        text,
  dni_paciente        text,
  resumen             text,                          -- resumen comprimido de la conversación
  paso_followup       integer not null default 0,    -- 0..8 (8 = fuera de la cola de recontacto)
  fecha               timestamptz default now(),     -- creación del lead
  fecha_actualizacion timestamptz default now()      -- última actividad (reinicia el followup)
);
create index if not exists leads_lena_id_usuario_idx on leads_lena (id_usuario);
create index if not exists leads_lena_followup_idx on leads_lena (paso_followup);
